<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-G1FQHVUJ" failures="2" tests="3" name="Default test" time="4.867" errors="0" timestamp="2021-02-09T16:07:45 IST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="4.38">
    <failure type="utilities.myAssertionException" message="error - 1">
      <![CDATA[utilities.myAssertionException: error - 1
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.014"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.018">
    <failure type="utilities.myAssertionException" message="error - 2">
      <![CDATA[utilities.myAssertionException: error - 2
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Default test -->
